const POPULATION_SIZE = 30;
const ELITE_COUNT = 5;
const INCLUDE_RANDOM_NETWORKS = true;

const GRAVITY = 0.03;

const START_HEIGHT = 150;
const HEIGHT_VARIABLE_PART = 250;
const START_HEIGHT_VARIANCE = 30;
const ROUNDS_PER_GENERATION = 8;

const ROCKET_LEARNING_RATE = 0.00001;
const ROCKET_FUEL = 80;
const ROCKET_POWER = 0.13;
const ROCKET_NETWORK_LAYERS = [3, 2, 1];
const ROCKET_FUEL_COST = 0.001;
const ROCKET_CRASH_MIN_VELOCITY = 1;
